// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaN4t3HnFY5SrWyx2pmD4dDWSkj3nIxw',
    appId: '1:905804218332:web:1693956984132c8ada5919',
    messagingSenderId: '905804218332',
    projectId: 'visionaryguidance',
    authDomain: 'visionaryguidance.firebaseapp.com',
    storageBucket: 'visionaryguidance.firebasestorage.app',
    measurementId: 'G-XH6TFQ9SP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_LBEmXI6-AgXUx66A1z3ZfRDtjjtYSlo',
    appId: '1:905804218332:android:3c9d71e52fd144bdda5919',
    messagingSenderId: '905804218332',
    projectId: 'visionaryguidance',
    storageBucket: 'visionaryguidance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD97qL3zN5hipz3Wg01r13G9V700g08r50',
    appId: '1:905804218332:ios:ce2117c8443ebd2bda5919',
    messagingSenderId: '905804218332',
    projectId: 'visionaryguidance',
    storageBucket: 'visionaryguidance.firebasestorage.app',
    iosBundleId: 'com.example.visionaryGuidance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD97qL3zN5hipz3Wg01r13G9V700g08r50',
    appId: '1:905804218332:ios:ce2117c8443ebd2bda5919',
    messagingSenderId: '905804218332',
    projectId: 'visionaryguidance',
    storageBucket: 'visionaryguidance.firebasestorage.app',
    iosBundleId: 'com.example.visionaryGuidance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBaN4t3HnFY5SrWyx2pmD4dDWSkj3nIxw',
    appId: '1:905804218332:web:b8d0e4f8e4c24a47da5919',
    messagingSenderId: '905804218332',
    projectId: 'visionaryguidance',
    authDomain: 'visionaryguidance.firebaseapp.com',
    storageBucket: 'visionaryguidance.firebasestorage.app',
    measurementId: 'G-EBQVRKZ21K',
  );
}
